language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install --dev
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
